# Generated by Django 3.1.6 on 2022-01-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_answer_is_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='q_choice',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
