# Generated by Django 3.1.6 on 2022-01-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_a_completion_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
