# Generated by Django 3.1.6 on 2022-02-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_submit_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submits',
            field=models.IntegerField(default=0),
        ),
    ]
