# Generated by Django 3.1.6 on 2022-02-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_project_submits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='os',
            field=models.CharField(max_length=1000),
        ),
    ]
