# Generated by Django 3.1.6 on 2022-04-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20220210_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_image',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
